### ISSUE TITLE
Home Assistant Addon Help

### ISSUE THREAD

**Issue by billythunder88** [gordlea/home-assistant-addons#36]
I cannot get the addon (2.0.1) to talk to home assistant or the MQTT addon. 

with just the ip address of the mqtt server
![image](https://github.com/gordlea/home-assistant-addons/assets/73123501/1e5cfaa4-4905-4ccb-b70f-6fe825d25f46)

with mqtt://10.x.x.x:1883
![image](https://github.com/gordlea/home-assistant-addons/assets/73123501/b5fe1355-87a2-40f1-9853-864ab3443889)

any idea how to overcome these errors?  Thanks!

**Comment by gordlea** [comment]
https://github.com/gordlea/fireboard2mqtt/issues/8#issuecomment-1656749749

**Comment by gordlea** [comment]
This should be fixed with gordlea/fireboard2mqtt#40
