### ISSUE TITLE
Generic Docker image

### ISSUE THREAD

**Issue by scottshanafelt** [gordlea/home-assistant-addons#45]
Is there a generic docker image available that doesn't require HA supervisor?  I'm running Home Assistant in a docker, making addons not usable.   Thanks

**Comment by gordlea** [comment]
Yes there is now, see: 

Docker hub: [fireboard2mqtt](https://hub.docker.com/r/gordlea/fireboard2mqtt)
Github: [gordlea/fireboard2mqtt](https://github.com/gordlea/fireboard2mqtt)
